FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backup ./backup

RUN mkdir -p /app/storage /app/temp

CMD ["uvicorn", "backup.main:app", "--host", "0.0.0.0", "--port", "8001"]
